volumes:
  static:
  pgdbdata: null

services:
  #  postgres:
  #    image: postgres:alpine
  #    container_name: pgdb
  #    environment:
  #      - POSTGRES_USER=postgres
  #      - POSTGRES_PASSWORD=postgres
  #      - POSTGRES_DB=octocrm
  #      - TZ=Europe/Kyiv
  #    ports:
  #      - '7432:5432'
  #    volumes:
  #      - pgdbdata:/var/lib/postgresql/data/
  #    restart: always
  offer_wall:
    build: .
    volumes:
      - ./offerWall:/opt/offerWall
    container_name: offer_wall
    command: bash -c "python3 manage.py migrate && gunicorn --bind 0.0.0.0:8000 --reload --workers 1 offerWall.wsgi:application"
    environment:
      - ENVIRON=DEVELOPMENT
    ports:
      - '8000:8000'
    restart: on-failure
