# Generated by Django 5.1.3 on 2024-11-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusion',
            fields=[
                ('click_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('excluded_offers', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
